# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: "DDD in Action: Strategies and tactics for Java solutions"
site_description: "DDD in action Workshop: Strategies and tactics for Java solutions"
site_author: "Karina Varela and Otávio Santana"
repo_url: https://github.com/ultimate-engineer/ddd-workshop
edit_uri: ""
copyright: "Developed with Ultimate Sophistication"
extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang: en
  - awesome-pages: #https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
      collapse_single_pages: true
  - enumerate-headings: # https://github.com/timvink/mkdocs-enumerate-headings-plugin
      toc_depth: 0
      strict: true
      increment_across_pages: true
      exclude:
        - index.md
        - more/sample_projects.md
  - git-revision-date-localized:
      type: iso_date
  - mermaid2:
      arguments:
        theme: default
        securityLevel: 'strict'

extra:
  generator: false

theme:
  name: material
  navigation_depth: 4
  locale: en
  generator: false
  icon:
    repo: fontawesome/brands/github-alt
    logo: material/library
    admonition:
      info: material/human-male-board
      note: material/rocket-launch
  palette:
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
        primary: light-blue
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode


  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.prune
    - toc.follow
    - navigation.top
    - content.code.annotate


markdown_extensions:
  - abbr
  - pymdownx.snippets
  - meta
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
